[uwsgi]
module = wsgi:app

master = true
processes = 2

socket = /home/ec2-user/api-server/api-server.sock
chmod-socket = 664
uid = ec2-user
gid = nginx
vacuum = true

die-on-term = true

# Logging configuration
logto = /home/ec2-user/api-server/uwsgi.log
log-date = true
logfile-chmod = 644
log-format = [%(addr)] [%(time)] [%(method)] [%(uri)] [%(proto)] [%(status)] [%(msecs)] [%(referer)] [%(uagent)]
log-4xx = true
log-5xx = true

# Optional: Set log level (0-4)
# 0: no logging
# 1: errors only
# 2: warnings
# 3: info
# 4: debug
log-level = 4
