# generated by datamodel-codegen:
#   filename:  oas.yaml
#   timestamp: 2025-03-16T11:15:01+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import Field, RootModel

from recommender.base import RecBaseModel


class Swimming(RecBaseModel):
    available: bool
    closed: Optional[bool] = None
    capacity: Optional[float] = None


class Gym(RecBaseModel):
    available: bool
    closed: Optional[bool] = None
    capacity: Optional[float] = None


class ActivityEnum(str, Enum):
    Swimming = 'Swimming'
    Football = 'Football'
    Gym = 'Gym'
    Wading = 'Wading'
    Indoor = 'Indoor'
    Badminton = 'Badminton'
    Table_tennis = 'Table_tennis'
    Netball = 'Netball'
    Volleyball = 'Volleyball'
    Basketball = 'Basketball'
    Athletics = 'Athletics'
    Soccer = 'Soccer'
    Rugby = 'Rugby'
    Tennis = 'Tennis'
    Squash = 'Squash'
    Hockey = 'Hockey'
    Petanque = 'Petanque'
    Gateball = 'Gateball'
    Lawn_bowl = 'Lawn_bowl'
    Pickleball = 'Pickleball'


class AgeRange(str, Enum):
    Children = 'Children'
    Adult = 'Adult'
    Senior = 'Senior'


class User(RecBaseModel):
    username: Optional[str] = Field(
        None, description='unique user name', examples=['dangkhoa']
    )
    activities: Optional[List[ActivityEnum]] = None
    age_range: Optional[AgeRange] = None
    location: Optional[List[float]] = Field(
        None, description='Location of entity (Lat, Lng)'
    )


class Facility(RecBaseModel):
    name: str = Field(..., description='facility name')
    address: Optional[str] = Field(None, description='facility address')
    activities: Optional[List[ActivityEnum]] = None
    age_range: Optional[List[AgeRange]] = None
    location: Optional[List[float]] = Field(
        None, description='Location of entity (Lat, Lng)'
    )
    coordinates: Optional[List[List[float]]] = None
    swimming: Swimming
    gym: Gym
