# generated by datamodel-codegen:
#   filename:  oas.yaml
#   timestamp: 2025-02-21T07:55:31+00:00

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


class GymType(Enum):
    gym = 'gym'
    swimming_pool = 'swimming_pool'
    park = 'park'


class Activity(Enum):
    indoor = 'indoor'
    outdoor = 'outdoor'
    both = 'both'


class AgeRange(Enum):
    children = 'children'
    adult = 'adult'
    senior = 'senior'


class User(BaseModel):
    name: str = Field(..., description='unique user name', example='dangkhoa')
    area: Optional[str] = Field(None, description='living area (town name)')
    prefer: Optional[Activity] = None
    age: Optional[AgeRange] = None


class Facility(BaseModel):
    name: str = Field(..., description='facility name')
    area: Optional[str] = Field(None, description='facility location')
    activity: Optional[Activity] = None
    age: Optional[AgeRange] = None
    gym_type: Optional[GymType] = None
    capacity: Optional[float] = None
    lat: Optional[float] = None
    lon: Optional[float] = None
