# generated by datamodel-codegen:
#   filename:  oas.yaml
#   timestamp: 2025-03-06T13:27:02+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field, RootModel


class ActivityEnum(Enum):
    Swimming = 'Swimming'
    Football = 'Football'
    Gym = 'Gym'
    Wading = 'Wading'
    Indoor = 'Indoor'
    Badminton = 'Badminton'
    Table_tennis = 'Table_tennis'
    Netball = 'Netball'
    Volleyball = 'Volleyball'
    Basketball = 'Basketball'
    Athletics = 'Athletics'
    Soccer = 'Soccer'
    Rugby = 'Rugby'
    Tennis = 'Tennis'
    Squash = 'Squash'
    Hockey = 'Hockey'
    Petanque = 'Petanque'
    Gateball = 'Gateball'
    Lawn_bowl = 'Lawn_bowl'
    Pickleball = 'Pickleball'


class Activity(RootModel[List[ActivityEnum]]):
    root: List[ActivityEnum]


class AgeRange(Enum):
    Children = 'Children'
    Adult = 'Adult'
    Senior = 'Senior'


class Location(RootModel[List[float]]):
    root: List[float] = Field(
        ..., description='Location of entity (Lat, Lng)', max_length=2, min_length=2
    )


class User(BaseModel):
    username: Optional[str] = Field(
        None, description='unique user name', examples=['dangkhoa']
    )
    activities: Optional[Activity] = None
    age_range: Optional[AgeRange] = None
    location: Optional[Location] = None


class Facility(BaseModel):
    name: str = Field(..., description='facility name')
    address: Optional[str] = Field(None, description='facility address')
    activities: Optional[Activity] = None
    age_range: Optional[List[AgeRange]] = None
    location: Optional[Location] = None
    coordinates: Optional[List[Location]] = None
