[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "recommender"
requires-python = ">=3.10"
dynamic = ["version"]
dependencies = [
    "datamodel-code-generator>=0.28.1",
    "faiss-cpu>=1.10.0",
    "fastapi[standard]>=0.115.8",
    "packaging>=24.2",
    "pip>=25.0.1",
    "pymongo[srv]>=4.11.1",
    "python-dotenv>=1.0.1",
    "starlette>=0.45.3",
    "typer>=0.15.1",
    "uvicorn>=0.34.0",
]

[tool]

[tool.hatch.version]
path = "src/recommender/__about__.py"

[tool.hatch.build.targets.wheel]
packages = ["src/recommender"]

[dependency-groups]
dev = [
    "faker>=36.1.1",
    "jupyterlab>=4.3.5",
    "shapely>=2.0.7",
]
